version: '3'

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: nuxt-app
    restart: always
    ports:
      - "3082:3082"
    environment:
      - DOCKER_BUILDKIT=1
      - COMPOSE_DOCKER_CLI_BUILD=1
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
